### ISSUE TITLE
There is this white overlap after clicking on the resource url

### ISSUE THREAD

**Issue by Nikhil-NP** [ayushsharma74/web-dev-resources#1]
![Screenshot 2024-12-15 211754](https://github.com/user-attachments/assets/0874b998-0c17-4492-a3ac-99cb50f1509a)
![Screenshot 2024-12-15 211930](https://github.com/user-attachments/assets/5b0a6b1b-9043-4b78-baad-795ae23e4836)

leme know i if you not solving this right now ,
 give me some time i am pre occupied right now  with something else i will try to solve it

**Comment by ayushsharma74** [comment]
Thanks for Pointing out, i'll look into it
